Update functions

diff --git a/src/cuser b/src/cuser
--- a/src/cuser
+++ b/src/cuser
@@ -2,6 +2,11 @@
 
 OPTIND=1 
 
+if [[ "$(id -u)" != "0" ]]; then
+  echo -e "\e[1;31mError:\e[0m: Este script debe ser ejecutado como superusuario"
+  exit 1
+fi
+
 Help(){
   echo -e "\033[1;32mCuser\033[0m, version 1.0\n"
   echo -e "  Sintaxis: cuser -n <nombre> -g <grupo> -s <shell> -m\n"
@@ -13,6 +18,23 @@ Help(){
   echo -e "\n"
 }
 
+createUser(){
+
+  local user=$1
+  local group=$2
+  local shell=$3
+  local homeDir=$4
+
+  if [[ -z $user ]]; then
+    echo -e "\e[1;31mError:\e[0m No se introdujo un nombre de usuario"
+  elif [[ $homeDir == "y" ]]; then
+    useradd -m -G $group -s $shell $user
+    echo -e "\nUsuario creado: \e[1;32m$user\e[0m \nAgregado a grupo(s): \e[1;33m$group\e[0m \nDirectorio en /home: Si\nShell:$shell\n"
+  else
+    useradd -G $group -s $shell $user
+    echo -e "\nUsuario creado: \e[1;32m$user\e[0m \nAgregado a grupo(s): \e[1;33m$group\e[0m \nDirectorio en /home: No\nShell:$shell\n"
+  fi
+}
 
 if [[ -z $* ]]; then
 
@@ -49,13 +71,7 @@ if [[ -z $* ]]; then
 
   done
 
-  if [[ $directorio == "y" ]]; then
-    useradd -m -G $addGroup -s $mainShell $nombreUsuario
-    echo -e "\nUsuario creado: \e[1;32m$nombreUsuario\e[0m \nAgregado a grupo(s): \e[1;33m$addGroup\e[0m \nDirectorio en /home: Si\nShell:$mainShell\n"
-  else
-    useradd -G $addGroup -s $mainShell $nombreUsuario
-    echo -e "\nUsuario creado: \e[1;32m$nombreUsuario\e[0m \nAgregado a grupo(s): \e[1;33m$addGroup\e[0m \nDirectorio en /home: No\nShell:$mainShell\n"
-  fi
+  createUser $nombreUsuario $addGroup $mainShell $directorio
 
   echo -n "¿Desea asignar una contraseña? [y/n]"
   read password
@@ -66,7 +82,6 @@ if [[ -z $* ]]; then
 
   exit 1
 fi
-
 
 while getopts "hn:g:s:mv" opt; do
   case ${opt} in
@@ -84,23 +99,9 @@ while getopts "hn:g:s:mv" opt; do
       shell=${OPTARG}
       ;;
     m)
-      homeDir=1
+      homeDir="y"
       ;;
   esac
 done
 
-
-if [[ -z $nombre ]]; then
-  echo -e "\e[1;31mError:\e[0m No se introdujo un nombre de usuario"
-else
-  if [[ $homeDir == 1 ]]; then
-    useradd -m -G $grupos -s $shell $nombre
-    echo -e "Usuario creado: \e[1;32m$nombre\e[0m \nAgregado a grupo(s): \e[1;33m$grupos\e[0m \nDirectorio en /home: Si \nShell:$shell"
-  else
-    useradd -G $grupos -s $shell $nombre
-    echo -e "Usuario creado: \e[1;32m$nombre\e[0m \nAgregado a grupo(s): \e[1;33m$grupos\e[0m \nDirectorio en /home: No \nShell:$shell"
-  fi
-
-fi
-
-
+createUser $nombre $grupos $shell $homeDir
